CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
# GPUS: (0,1,2,3)
GPUS: (0,)
OUTPUT_DIR: 'hrnet_output'
LOG_DIR: 'hrnet_log'
WORKERS: 8
PRINT_FREQ: 10

DATASET:
  DATASET: custom
  ROOT: '/media/cjh/T7_Shield_1/'
  TRAIN_SET: '/divide_lists/train_hrnet.lst'
  TEST_SET: '/divide_lists/test_hrnet.lst'
  NUM_CLASSES: 29
  RESIZE_SHAPE: [1024, 2048]
  USE_JSON: true
MODEL:
  NAME: seg_hrnet_ocr
  # ALIGN_CORNERS: False
  NUM_OUTPUTS: 2
  PRETRAINED: '/home/cjh/workspace/caselab/data_project/data_project/hrnet_output/epoch_73.346.pth'
  EXTRA:
    FINAL_CONV_KERNEL: 1
    STAGE1:
      NUM_MODULES: 1
      NUM_RANCHES: 1
      BLOCK: BOTTLENECK
      NUM_BLOCKS:
      - 4
      NUM_CHANNELS:
      - 64
      FUSE_METHOD: SUM
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      - 384
      FUSE_METHOD: SUM
LOSS:
  USE_OHEM: true
  OHEMTHRES: 0.95
  OHEMKEEP: 2097152
  BALANCE_WEIGHTS: [0.3, 1]
TRAIN:
  IMAGE_SIZE:
  - 1024
  - 512
  BASE_SIZE: 2048
  BATCH_SIZE_PER_GPU: 1
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 1000
  RESUME: true
  OPTIMIZER: sgd
  LR: 2e-6
  WD: 0.0001
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: true
  MULTI_SCALE: true
  DOWNSAMPLERATE: 1
  IGNORE_LABEL: 255
  SCALE_FACTOR: 16
  VALIDATION_TERM: 50
  SAVE_MODEL_TERM: 1
TEST:
  IMAGE_SIZE:
  - 2048
  - 1024
  BASE_SIZE: 2048
  BATCH_SIZE_PER_GPU: 1
  FLIP_TEST: false
  MULTI_SCALE: false
  NUM_SAMPLES: None
  MODEL_FILE: '/home/cjh/workspace/caselab/data_project/data_project/hrnet_output/epoch_73.346.pth'